dist/css/custom.css
dist/index.html
dist/js/projects.js

- language icon row now wraps on project cards
- social, support, and donate sections now display correctly on mobile
- banner overlay text now using `vh` instead of `px` for absolute positioning
- Fixes #12

fix mobile display issues

---

dist/js/projects.js

add project docs links

---

dist/discord.html
dist/index.html
dist/privacy.html
dist/terms.html

- update meta tags
This should show a large preview on Discord (and probably other platforms)
Current:
Future?

update meta tags

---

dist/css/custom.css
dist/feedback.html

- add feedback board ([feature upvote](https://feedback.lizardbyte.dev/)) embedded as iframe

add feedback board

---

dist/feedback.html
dist/index.html
dist/js/projects.js
dist/support.html

- add support page
- separate support section on home page from social and donate
- remove rounded corners from some elements

add support page

---

.github/workflows/build.yml

fix yaml-lint errors

---

dist/index.html

- update social/donate sections (Use badges with counters where possible.)

update social/donate sections

---

dist/js/projects.js

- fix project banner size
- Smaller image size used, will reduce load time when images are not cached.

fix project banner size

---

README.rst
dist/discord.html
dist/feedback.html
dist/index.html
dist/js/crowdin.js
dist/privacy.html
dist/support.html
dist/terms.html

- add crowdin integration
- add readme

add crowdin integration

---

dist/js/crowdin.js

- use built in methods for changing button position
- change styling of button, menu, etc.

update crowdin button

---

.github/workflows/build.yml
.gitignore
dist/js/crowdin.js

- add locale directories
This will require changing language detection type in CrowdIn.
After adding language switched, Scollspy in no longer working properly. This PR fixes that.

add locale directories

---

.github/workflows/build.yml

copy entire dist directory

---

dist/js/crowdin.js

Add German and Italian languages to CrowdIn language selector.

add additional languages

---

dist/js/crowdin.js

- update crowdin distribution
Probably need to find a way to automate this.

fix crowdin distribution

---

dist/index.html
dist/js/discord.js
dist/js/navbar.js

Using full source path will allow sites, such as ThemerrDB, to access these resources.

sources: use full source paths

---

README.rst

Fix shields badge per this breaking change: https://github.com/badges/shields/issues/8671

documentation: fix shields badge

---

.github/workflows/build.yml

undo remove dot files

---

.github/workflows/build.yml

Ensure page is built without jekyll as it doesn't handle files prefixed with a `.` well.

build: fix jekyll build

---

dist/discord.html
dist/feedback.html
dist/index.html
dist/js/crowdin.js
dist/js/crowdin_web_widget.js
dist/privacy.html
dist/support.html
dist/terms.html

Adds crowdin web widget, which allows visitors to the website to help with translations.

feat(localization): add crowdin web widget

---

dist/discord.html
dist/feedback.html
dist/index.html
dist/js/navbar.js
dist/js/projects.js
dist/support.html

- Add ignore class for crowdin translations to simplify translation process.
- Re-word read the docs paragraph on support page, to simplify translation.

fix(localization): ignore specific strings

---

dist/index.html
dist/support.html

This PR adjusts the style of social badges to match those in the org's GitHub profile.

refactor: update style of social badges

---

dist/dev.html
dist/js/dev_dashboard.js
dist/js/projects.js

This PR adds a dev dashboard for quick overview of repos in the org.

feat: add dev dashboard

---

dist/support.html

Update docs url in `support.html`.

fix: update org docs url

---

README.rst

docs: update localization information

---

dist/js/discord.js

Rewrite discord.js to remove jQuery dependency, this version of the file will be also used by Sunshine

refactor: rewrite discord.js to remove jQuery dependency

---

dist/dev.html
dist/js/dev_dashboard.js

Add some service buttons to top of dev dashboard, and remove tracking of default branch.

feat(dev): add service buttons

---

dist/dev.html

feat(dev): add copr button

---

dist/dev.html

Add SonarCloud button and use official cloudsmith icon.

feat(dev): add sonarcloud

---

README.rst

docs(locale): update crowdin graph

---

dist/support.html

Update GitHub discussions section

fix(support): update github discussions section

---

dist/.well-known/org.flathub.VerifiedApps.txt

Add flathub verification token.
This may or may not work. See: https://github.com/flathub/flathub/issues/5663

feat(flathub): add verification

---

.github/workflows/build.yml

build(pages): ensure hidden files are included

---

dist/support.html

fix(social): remove facebook group

---

.github/workflows/jekyll-build.yml

Base URL is not correct. A better fix should be made in the future, but this should get things working for now.

fix(website): ensure correct base url is used

---

.github/workflows/jekyll-build.yml

ci(site): fix base urls

---

.github/workflows/jekyll-build.yml

ci(deploy): fix nojekyll directory

---

_layouts/release.html

Added a release layout to use for automated blog posts on release events.

feat(jekyll): add release layout for automated blog posts

---

_includes/crowdin-scripts.html
_includes/discord-widgetcrate.html
index.html

Bump @lizardbyte/shared-web. This change drops the crowdin-web-widget.

build(deps)!: bump @lizardbyte/shared-web from 2024.921.191855 to 2025.321.1458

---

scripts/readthedocs_build.sh

fix(rtd): fix env variable typo

---

_includes/support.html

The support url was relative to the repo/project instead of to the main website.

fix(support): fix href for support includes

---

assets/js/projects.js

Projects, such as Sunshine, have a special RTD project for previewing gh-pages builds for PRs. These should not be included in the project card.

fix(projects): do not include docs for PR preview projects

---

README.md

docs(readme): add crowdin contributors

---

README.md

See https://github.com/LizardByte/contributors/pull/13

docs(readme): update crowdin image url

---

_config_theme.yml

Bump beautiful-jekyll submodule.

build(deps): bump beautiful-jekyll submodule

---

_sass/styles.scss

This PR is needed for https://github.com/LizardByte/Sunshine/pull/3803

feat: add class to invert image colors

---

_sass/styles.scss

More fixes for https://github.com/LizardByte/Sunshine/pull/3803

fix(styles): add icon sizes and allow invert on all images

---

_sass/styles.scss

Another fix for https://github.com/LizardByte/Sunshine/pull/3803

fix(styles): reverse invert on hover

---

_data/licenses.yml
gamepad-tester.html

chore(deps): bump LizardByte/gamepad-helper from 2025.501.232754 to 2025.517.134257

---

_config_theme.yml
assets/js/changelog-links.js

Fix release notes changelog URLs using javascript.

fix(blog): make changelog urls clickable

---

_posts/releases/sunshine/2025-01-18-v2025.118.151840.md
_posts/releases/sunshine/2025-01-22-v2025.122.141614.md
_posts/releases/sunshine/2025-06-28-v2025.628.4510.md

Adds thumbnail image to release blog posts.

style(blog): add thumbnail-img for release posts

---

_data/licenses.yml

Fixes licenses due to changes in https://github.com/LizardByte/LizardByte.github.io/pull/250

docs: Update licenses.yml with Beautiful Jekyll Next

---

_sass/styles.scss

Style list groups similar to rest of site.

fix: style list-groups

---

_sass/styles.scss

Previous fix (https://github.com/LizardByte/LizardByte.github.io/pull/263) did not work.

fix(style): alternate fix for list-group styling

---

assets/js/projects.js

This PR allows showing forks on the main website, if they have the "featured-fork" repo topic.

feat(projects): showcase featured forks

---

assets/js/projects.js

This PR adds a commit activity graph to project cards.

feat(projects): add commit activity

---

assets/js/projects.js

Swapped the FontAwesome icon for documentation links with a ReadTheDocs SVG image for better branding and visual clarity. The new image includes appropriate alt text, title, and sizing.

fix: Replace docs icon with ReadTheDocs SVG image
